# Generated by Django 4.2.7 on 2023-12-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslist',
            name='player_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
