# Generated by Django 4.2.7 on 2023-12-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerslist_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerslist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
